name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy MkDocs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.21
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
